name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Test
        run: make test
      - name: "Build"
        run: make build
